" Name:         One Candy Dark
" Author:       KacperBiedka <kacper.biedka.00@gmail.com>
" Maintainer:   Sarah Evermore <sarah.evermore.02@gmail.com>
" License:      Vim License (see `:help license`)
" Last Updated: Wed Mar 20 09:53:06 2024

" Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'one_candy_dark'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)

" vim: et ts=8 sw=2 sts=2
